export { default as playIcon } from "./play.svg";
export { default as pauseIcon } from "./pause.svg";
export { default as fullscreenOnIcon } from "./arrows-pointing-out.svg";
export { default as fullscreenOfIcon } from "./arrows-pointing-in.svg";
export { default as shadersOnIcon } from "./sparklesOn.svg";
export { default as shadersOffIcon } from "./sparklesOff.svg";
export { default as openFile } from "./openFile.svg";
export { default as muteOf } from "./mute-of.svg";
export { default as muteOn } from "./mute-on.svg";
